### PR TITLE
Move password constraints to appsettings

### PR DESCRIPTION
**Pull request by phatcher**
Sort of thing that a user might want to change but shouldn't require a code change

### CODE REVIEW

**Comment by poppastring** [comment]
@phatcher  Thanks for fixing this, I think this is a great idea!

I am thinking about the case where someone installs the latest version over existing an existing deployment of dasblog-core. Essentially the assumption here is that the config file has been update too. 

Would it be possible to add code that allows me to assume a set of default values in the event that the user does not update the file? (could be the appsettings.Production.json file).

**Comment by phatcher** [comment]
How about making the constructor of Startup slightly different that brings in an optional appsettings.{env}.json e.g.

	public Startup(IHostEnvironment env)
	{
		hostingEnvironment = env;

		SiteSecurityConfigPath = Path.Combine("Config", $"siteSecurity.{env.EnvironmentName}.config");
		IISUrlRewriteConfigPath = Path.Combine("Config", $"IISUrlRewrite.{env.EnvironmentName}.config");
		SiteConfigPath = Path.Combine("Config", $"site.{env.EnvironmentName}.config");
		MetaConfigPath = Path.Combine("Config", $"meta.{env.EnvironmentName}.config");
		
		var builder = new ConfigurationBuilder()
			.SetBasePath(env.ContentRootPath)
			.AddXmlFile(SiteConfigPath, optional: false, reloadOnChange: true)
			.AddXmlFile(MetaConfigPath, optional: false, reloadOnChange: true)
			.AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
			.AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true)
			.AddEnvironmentVariables();

		Configuration = builder.Build();
		
		BinariesPath = new DirectoryInfo(Path.Combine(env.ContentRootPath, Configuration.GetValue<string>("BinariesDir"))).FullName;
		ThemeFolderPath = new DirectoryInfo(Path.Combine(hostingEnvironment.ContentRootPath, "Themes", Configuration.GetSection("Theme").Value)).FullName;
		LogFolderPath = new DirectoryInfo(Path.Combine(hostingEnvironment.ContentRootPath, Configuration.GetSection("LogDir").Value)).FullName;
		BinariesUrlRelativePath = "content/binary";
	}

.NET Core will always have an environment so we don't need the current check for IsNullOrWhiltespace.  Also, since EnviromentVariables are last and so take priority, you can set these properties during the deployment or from the Azure portal since they are picked up from appsettings.xxx.json rather than the custom configuration files.

BTW For a real blog where do you keep your production settings files, what I've done is set up a private repo with a separate branch that contains these files, I then merge code on to that branch and then triggers the CI/CD build.

**Comment by poppastring** [comment]
@phatcher I like that idea (thanks for the cleanup), could you update this this PR with this code?

My environment settings are set to "production" so my config files, are as follows: **site.Production.config**. The standard deployment completely ignores these files (does not delete them) I take regular backs so I do not need feel the need for a private repo branch.

**Comment by poppastring** [comment]
Thanks @phatcher !

#close #501

**Pull request merged**
