### PR TITLE
post edit tag helper

### PR DESCRIPTION
**Pull request by chillryan**
#6 post edit button
1st draft as i'm not sure if the REST actions are set yet.

### CODE REVIEW

**Comment by poppastring** [comment]
Thanks for the pull request! I will review this tomorrow afternoon and get back to you.

**Comment by chillryan** [comment]
Looking forward to it! I had some free time, I hope reviewing it isn't too daunting 😁

**Comment by chillryan** [comment]
@poppastring will do. that's what i had at first but wasn't sure what the actual URL would be (that's why i had that TODO there LOL)

I also double checked my settings and by default, my tab size is 4 for both C# and HTML. not sure if the .editorconfig is doing something funky (we use spaces at the job) so i'll take a look.

**Comment by chillryan** [comment]
@poppastring I checked, double checked, and tripled check... my tabs are set at 4, keep tabs, smart indenting. I don't have extra tabs in the files I've edited. Any ideas?

**Comment by poppastring** [comment]
@chillryan Very strange, I am going to assume there is a problem with the GitHub diff tool and consume your change anyway. If there are problems in VS after that point we can address it relatively quickly. Should not be a big deal.

Thanks for looking.

**Comment by poppastring** [comment]
@chillryan It does look good this time actually. All the tabs/spaces look fine! Many thanks!!!

**Pull request merged**
