### PR TITLE
Flip to .NET Core HostBuilder and suppress the Kestrel header

### PR DESCRIPTION
**Pull request by phatcher**
.NET Core 3.1 preferred startup

### CODE REVIEW

**Comment by poppastring** [comment]
@phatcher

**Comment by poppastring** [comment]
@phatcher Not sure what this PR does, the docs are not great on exactly what this accomplishes.

**Comment by phatcher** [comment]
Here's a [SO answer](https://stackoverflow.com/questions/52085806/what-is-the-difference-between-iwebhost-webhostbuilder-buildwebhost) I think that covers it. Useful bit is at the end...

"The generic host introduced with ASP.NET Core 3.0 and .NET Core 3.0 basically replaces the previous IWebHost and IWebHostBuilder. It follows the very same architecture and idea but is simply reduced to non-web tasks so that it can work with a number of different purposes. ASP.NET Core then just builds on top of this generic host."

So I was just updating to the current idiomatic code.

**Comment by poppastring** [comment]
@phatcher I had to roll this back as it broke the Selenium testing project as it is looking for IWebHost.

**Pull request merged**
